// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Odoc = require("./Odoc.bs.js");
var Common = require("./Common.bs.js");
var Logger = require("./Logger.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var BuckleScript = require("./BuckleScript.bs.js");

function support_files(flags, out_dir) {
  Logger.info("Copying support files (CSS, JS) into " + (String(out_dir) + ""));
  Logger.debug("Making sure output dir " + (String(out_dir) + " exists..."));
  Common.mkdirp(out_dir);
  Odoc.support_files(out_dir);
  return Logger.info("Done ✅");
}

function build(flags, out_dir, pkg_name, src_dir, lib_dir) {
  var $$package = BuckleScript.$$package(pkg_name, src_dir, lib_dir);
  Logger.info("Compiling documentation for package \"" + (String(pkg_name) + "\"..."));
  Logger.debug("Making sure output dir " + (String(out_dir) + " exists..."));
  Common.mkdirp(out_dir);
  Logger.debug("Looking for .cmti files in " + (String(lib_dir) + ""));
  Logger.debug("Compiling .cmti files into .odoc files...");
  var cmti_odocs = List.map((function (param) {
          return Odoc.cmti_to_odoc(lib_dir, pkg_name, param);
        }), $$package[/* cmtis */1]);
  Logger.debug("Done ✅");
  Logger.debug("Looking for .mld files in " + (String(src_dir) + ""));
  Logger.debug("Compiling .mld files into .odoc files...");
  var mld_odocs = List.map((function (param) {
          return Odoc.mld_to_odoc(lib_dir, src_dir, pkg_name, param);
        }), $$package[/* mlds */2]);
  Logger.debug("Done ✅");
  Logger.info("Generating .html files...");
  var odocs = Pervasives.$at(cmti_odocs, mld_odocs);
  List.map((function (param) {
          return Odoc.odoc_to_html(lib_dir, out_dir, param);
        }), odocs);
  return Logger.info("Done ✅");
}

exports.support_files = support_files;
exports.build = build;
/* Odoc Not a pure module */
