// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Operators = require("./Operators.bs.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Child_process = require("child_process");

function verbosity_string(param) {
  switch (param) {
    case 0 : 
        return "normal";
    case 1 : 
        return "quiet";
    case 2 : 
        return "verbose";
    
  }
}

function flags(debug, verbosity) {
  return /* record */[
          /* debug */debug,
          /* verbosity */verbosity
        ];
}

function run(cmd, args) {
  console.log(cmd, $$Array.of_list(args));
  var x = Child_process.spawnSync(cmd, $$Array.of_list(args));
  return Operators.Option[/* <|> */1](Operators.Option[/* |>> */0](Js_primitive.null_to_opt(x.status), (function (x) {
                    return x === 0;
                  })), false);
}

function exec(str) {
  return Child_process.execSync(str, { }).toString().trim();
}

exports.verbosity_string = verbosity_string;
exports.flags = flags;
exports.run = run;
exports.exec = exec;
/* child_process Not a pure module */
