// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function verbosity_string(param) {
  switch (param) {
    case 0 : 
        return "normal";
    case 1 : 
        return "quiet";
    case 2 : 
        return "verbose";
    
  }
}

function flags(debug, verbosity) {
  return /* record */[
          /* debug */debug,
          /* verbosity */verbosity
        ];
}

exports.verbosity_string = verbosity_string;
exports.flags = flags;
/* No side effect */
