// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var verbosity = /* record */[/* contents : Normal */0];

var info_prefix = "info: ";

function info(s) {
  var match = verbosity[0];
  if (match !== 1) {
    console.log(info_prefix + s);
    return /* () */0;
  } else {
    return /* () */0;
  }
}

var debug_prefix = "debug: ";

function debug(s) {
  var match = verbosity[0];
  if (match >= 2) {
    console.log(debug_prefix + s);
    return /* () */0;
  } else {
    return /* () */0;
  }
}

var error_prefix = "ERROR: ";

function error(s) {
  console.log(error_prefix + s);
  return /* () */0;
}

exports.verbosity = verbosity;
exports.info_prefix = info_prefix;
exports.info = info;
exports.debug_prefix = debug_prefix;
exports.debug = debug;
exports.error_prefix = error_prefix;
exports.error = error;
/* No side effect */
