// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Cli = require("./Cli.bs.js");
var VersionChecks = require("./VersionChecks.bs.js");

VersionChecks.check(/* () */0);

Cli.run(/* () */0);

/*  Not a pure module */
