// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function $pipe$great$great(x, f) {
  if (x !== undefined) {
    return Js_primitive.some(Curry._1(f, Js_primitive.valFromOption(x)));
  }
  
}

function $less$pipe$great(a, b) {
  if (a !== undefined) {
    return Js_primitive.valFromOption(a);
  } else {
    return b;
  }
}

var Option = /* module */[
  /* |>> */$pipe$great$great,
  /* <|> */$less$pipe$great
];

exports.Option = Option;
/* No side effect */
