// Generated by BUCKLESCRIPT VERSION 4.0.11, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function $pipe$great$great(x, f) {
  if (x !== undefined) {
    return Caml_option.some(Curry._1(f, Caml_option.valFromOption(x)));
  }
  
}

function $less$pipe$great(a, b) {
  if (a !== undefined) {
    return Caml_option.valFromOption(a);
  } else {
    return b;
  }
}

var Option = /* module */[
  /* |>> */$pipe$great$great,
  /* <|> */$less$pipe$great
];

exports.Option = Option;
/* No side effect */
