// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Logger = require("./Logger.bs.js");
var Operators = require("./Operators.bs.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Child_process = require("child_process");

function run(cmd, args) {
  var full_cmd = cmd + List.fold_left((function (x, y) {
          return x + (" " + y);
        }), "", args);
  Logger.debug("Executing " + (String(full_cmd) + ""));
  var x = Child_process.spawnSync(cmd, $$Array.of_list(args));
  return Operators.Option[/* <|> */1](Operators.Option[/* |>> */0](Js_primitive.null_to_opt(x.status), (function (x) {
                    return x === 0;
                  })), false);
}

function exec(str) {
  return Child_process.execSync(str, { }).toString().trim();
}

function mkdirp(path) {
  if (Fs.existsSync(path)) {
    return 0;
  } else {
    Fs.mkdirSync(path, {
          recursive: true
        });
    return /* () */0;
  }
}

exports.run = run;
exports.exec = exec;
exports.mkdirp = mkdirp;
/* fs Not a pure module */
