// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var OS = require("./OS.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function check(param) {
  var good_switch = "4.02.3+buckle-master";
  var installed_switch = OS.exec("opam switch show");
  var has_good_switch = installed_switch === good_switch;
  if (!has_good_switch) {
    console.log(" 🔥 Could not find the needed opam switch: " + (String(good_switch) + (".\n\nInstead found: " + (String(installed_switch) + (".\n\nTo install it, make sure you have `opam` installed and execute:\n\n    opam switch create " + (String(good_switch) + "\n    eval \$(opam env)\n\nThen try again 🙌🏼\n"))))));
    Pervasives.exit(1);
  }
  var has_odoc_pkg = OS.run("opam", /* :: */[
        "show",
        /* :: */[
          "odoc",
          /* [] */0
        ]
      ]);
  var has_odoc_in_path = OS.run("which", /* :: */[
        "odoc",
        /* [] */0
      ]);
  if (!has_odoc_pkg) {
    console.log(" 🔥 Could not find the needed odoc package.\n\nTo install it, make sure you have `opam` installed and execute:\n\n    opam install odoc\n\nThen try again 🙌🏼\n");
    Pervasives.exit(2);
  }
  if (has_odoc_in_path) {
    return 0;
  } else {
    console.log(" 🔥 Could not find the needed odoc binary in your PATH.\n\nTo install it, make sure you have `opam` installed and execute:\n\n    opam install odoc\n\nThen try again 🙌🏼\n");
    return Pervasives.exit(3);
  }
}

exports.check = check;
/* OS Not a pure module */
