// Generated by BUCKLESCRIPT VERSION 4.0.11, PLEASE EDIT WITH CARE
'use strict';

var OS = require("./OS.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var opam = "opam";

var odoc = "odoc";

function check(param) {
  var has_opam_in_path = OS.run(opam, /* :: */[
        "--version",
        /* [] */0
      ]);
  if (!has_opam_in_path) {
    console.log(" 🔥 Could not find the needed odoc binary in your PATH.\n\nTo install it, follow instructions in: http://opam.ocaml.org/doc/Install.html\n\nThen try again 🙌🏼\n");
    Pervasives.exit(1);
  }
  var good_switch = "4.02.3+buckle-master";
  var installed_switch = OS.exec("" + (String(opam) + " switch show"));
  var has_good_switch = installed_switch === good_switch;
  if (!has_good_switch) {
    console.log(" 🔥 Could not find the needed opam switch: " + (String(good_switch) + (".\n\nInstead found: " + (String(installed_switch) + (".\n\nTo install it, make sure you have `opam` installed and execute:\n\n    opam switch create " + (String(good_switch) + "\n    eval \$(opam env)\n\nThen try again 🙌🏼\n"))))));
    Pervasives.exit(1);
  }
  var has_odoc_pkg = OS.run(opam, /* :: */[
        "show",
        /* :: */[
          odoc,
          /* [] */0
        ]
      ]);
  if (!has_odoc_pkg) {
    console.log(" 🔥 Could not find the needed odoc package.\n\nTo install it, make sure you have `opam` installed and execute:\n\n    opam install odoc\n\nThen try again 🙌🏼\n");
    Pervasives.exit(1);
  }
  var has_odoc_in_path = OS.run(odoc, /* :: */[
        "--version",
        /* [] */0
      ]);
  if (has_odoc_in_path) {
    return 0;
  } else {
    console.log(" 🔥 Could not find the needed odoc binary in your PATH.\n\nTo install it, make sure you have `opam` installed and execute:\n\n    opam install odoc\n\nThen try again 🙌🏼\n");
    return Pervasives.exit(1);
  }
}

exports.opam = opam;
exports.odoc = odoc;
exports.check = check;
/* OS Not a pure module */
