// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function run(param) {
  console.log("Hello, BuckleScript and Reason!");
  return /* () */0;
}

exports.run = run;
/* No side effect */
