// Generated by BUCKLESCRIPT VERSION 6.0.0-dev.1, PLEASE EDIT WITH CARE
'use strict';


function run(param) {
  console.log("Hello, BuckleScript and Reason!");
  return /* () */0;
}

exports.run = run;
/* No side effect */
